/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minestombasiclight;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        LightEngine classUnderTest = new LightEngine();

    }
}
